name: Build and deploy site

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build --production

    - name: Display current directory contents
      run: ls -al

    - name: Display dist directory contents
      run: ls -al dist/site-web

    - name: Deploy to gh-pages
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist/site-web
          git commit -m "generated"
          git push origin gh-pages
